baseURL = "https://blog.qaware.de/"
languageCode = "en-us"
title = "QAware | Software Engineering Blog"
theme = "qaware-blog-theme"
author = "QAware GmbH"
copyright = "Copyright Â© 2020, QAware GmbH; all rights reserved."
paginate = 11
enableEmoji = true

[params]
logo = "/images/qaware_logo.png"
kununu_name = "qaware"
twitter_handle = "qaware"
linkedin_company = "qaware-gmbh"
github_name = "qaware"
slideshare_name = "qaware"
youtube_channel = "UCmNf72xADnO57idipq9jvMg"
main_sections = ["blog"]
ga_analytics = "UA-45534590-1" # google analytics ID e.g UA-116386578-1
cookiebot = "4e938949-aa56-465e-9c2a-175bb6c31d81"

[markup]
   [markup.highlight]
     codeFences = true
     guessSyntax = false
     hl_Lines = ""
     lineNoStart = 1
     lineNos = true
     lineNumbersInTable = true
     # style = "monokai"
     noClasses = false
     tabWidth = 2
